/**
 * ============================================================
 * FIRESTORE SCHEMA DESIGN
 * Madurai Civic Intelligence System
 * ============================================================
 *
 * This file documents the Firestore collection schemas.
 * It is NOT executable — purely for documentation.
 * ============================================================
 */

// ─────────────────────────────────────────────────────────────────────────────
// Collection: complaints
// Path: complaints/{complaintId}
// ─────────────────────────────────────────────────────────────────────────────

const complaintSchema = {
  complaintId: "string (UUID v4)",
  source: "string — 'image' | 'audio'",
  status: "string — 'Open' | 'In Progress' | 'Resolved' | 'Escalated' | 'Verification Failed'",

  // Location
  latitude: "number",
  longitude: "number",
  wardNumber: "number | null",

  // Reporting
  reportedBy: "string — citizen ID or 'anonymous'",
  createdAt: "ISO 8601 timestamp string",
  updatedAt: "ISO 8601 timestamp string",

  // AI Analysis (from image)
  analysisResult: {
    waste_type: "string — 'Temple Waste' | 'Tourist Waste' | 'Mixed' | 'Biological Hazard' | ...",
    estimated_volume_m3: "number",
    detected_items: ["array of strings"],
    severity_score: "number (1-10)",
    priority_score: "number (1-10)",
    location_zone: "string",
    recommended_action: "string",
    confidence: "number (0.0-1.0)",
    redZoneFlag: "string | null",
    hazard_flags: {
      is_biological_hazard: "boolean",
      has_dead_animal: "boolean",
      has_biomedical_waste: "boolean",
      has_chemical_waste: "boolean",
    },
  },

  // Audio classification (from audio)
  transcription: "string | null",
  transcriptionConfidence: "number | null",
  classificationResult: {
    original_transcription: "string",
    english_translation: "string",
    category: "string",
    sub_category: "string",
    urgency: "string",
    action_required: "string",
    is_hazardous: "boolean",
    confidence: "number",
  },

  // Geocoding
  addressInfo: {
    formattedAddress: "string",
    locality: "string",
    city: "string",
    district: "string",
    state: "string",
    postalCode: "string",
  },

  // Escalation
  escalationId: "string | null",
  verificationStatus: "string | null",
  resolvedAt: "ISO 8601 timestamp | null",
  resolvedBy: "string | null",
  assignedUnit: "string | null",
};

// ─────────────────────────────────────────────────────────────────────────────
// Collection: verifications
// Path: verifications/{verificationId}
// ─────────────────────────────────────────────────────────────────────────────

const verificationSchema = {
  verificationId: "string (UUID v4)",
  complaintId: "string — references complaints/{complaintId}",
  workerId: "string — municipal worker ID",
  createdAt: "ISO 8601 timestamp",

  verificationResult: {
    same_location: "boolean",
    trash_removed: "boolean",
    fraud_probability: "number (0.0-1.0)",
    verification_status: "string — 'Approved' | 'Rejected' | 'Manual Review Required'",
    confidence: "number",
    observations: {
      location_match_evidence: "string",
      cleaning_evidence: "string",
      fraud_indicators: "string",
    },
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// Collection: hazardEscalations
// Path: hazardEscalations/{escalationId}
// ─────────────────────────────────────────────────────────────────────────────

const hazardEscalationSchema = {
  escalationId: "string",
  complaintId: "string",
  hazardType: "string — 'Dead Animal Removal' | 'Biomedical Waste' | 'Chemical/Hazardous Waste' | ...",
  status: "string — 'Notified' | 'In Progress' | 'Resolved'",
  createdAt: "ISO 8601 timestamp",

  location: {
    latitude: "number",
    longitude: "number",
    zone: "string",
  },

  disposalUnit: {
    name: "string",
    distanceMeters: "number | null",
  },

  notification: {
    smsTamil: "string",
    smsEnglish: "string",
    emailSubject: "string",
  },

  dispatchResult: {
    smsSent: "boolean",
    emailSent: "boolean",
  },

  agentLog: [
    {
      step: "number",
      action: "string",
      status: "string",
      result: "object | string",
    },
  ],
};

// ─────────────────────────────────────────────────────────────────────────────
// Collection: disposalUnits
// Path: disposalUnits/{unitId}
// Populated via Firebase Console or seed script — NOT generated by Cloud Functions
// ─────────────────────────────────────────────────────────────────────────────

const disposalUnitSchema = {
  unitId: "string",
  name: "string — e.g., 'Madurai CMWSSB Biomedical Unit'",
  contactPhone: "string (E.164 format)",
  contactEmail: "string",
  latitude: "number",
  longitude: "number",
  address: "string",
  capabilities: [
    "array of strings — 'Biomedical Waste' | 'Dead Animal Removal' | 'Chemical/Hazardous Waste'"
  ],
  operatingHours: "string — e.g., '24/7' | '8am-6pm'",
  isActive: "boolean",
  wardsCovered: ["array of ward numbers"],
  createdAt: "ISO 8601 timestamp",
  updatedAt: "ISO 8601 timestamp",
};

// ─────────────────────────────────────────────────────────────────────────────
// Collection: heritageRestorations
// Path: heritageRestorations/{jobId}
// ─────────────────────────────────────────────────────────────────────────────

const heritageRestorationSchema = {
  jobId: "string (UUID v4)",
  status: "string — 'Completed' | 'Failed'",
  createdAt: "ISO 8601 timestamp",
  latitude: "number | null",
  longitude: "number | null",
  locationDescription: "string | null",
  gcsUri: "string | null — gs://bucket/path/to/image.png",
  promptUsed: "string — Imagen generation prompt",
};

module.exports = {
  complaintSchema,
  verificationSchema,
  hazardEscalationSchema,
  disposalUnitSchema,
  heritageRestorationSchema,
};
